# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         knp-perl
version:      0.4.9
version_from: lib/KNP.pm
installdirs:  site
requires:
    Juman:                         0.5.7

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
